using FluentAssertions;
using QrMenu.Application.DTOs;
using QrMenu.Infrastructure.Services;
using Xunit;

namespace QrMenu.Tests;

public class RestaurantServiceTests
{
    [Fact] public async Task CreateRestaurant_ShouldGenerateSlug() { var db=TestDbFactory.CreateInMemory(); var svc=new RestaurantService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await svc.CreateAsync(new CreateRestaurantDto{Name="Bella Cucina",ThemeColor="#f00",CurrencyCode="TRY",CurrencySymbol="₺",SupportedLanguages="tr"},owner.Id); r.Slug.Should().Be("bella-cucina"); r.IsApproved.Should().BeFalse(); }
    [Fact] public async Task ToggleActive_ShouldFlipState() { var db=TestDbFactory.CreateInMemory(); var svc=new RestaurantService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id); await svc.ToggleActiveAsync(r.Id); var a=await svc.GetByIdAsync(r.Id); a!.IsActive.Should().BeFalse(); }
    [Fact] public async Task Approve_ShouldSetApproved() { var db=TestDbFactory.CreateInMemory(); var svc=new RestaurantService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id,false); await svc.ApproveAsync(r.Id); var a=await svc.GetByIdAsync(r.Id); a!.IsApproved.Should().BeTrue(); }
    [Fact] public async Task GetBySlug_NonExistent_ReturnsNull() { var db=TestDbFactory.CreateInMemory(); var svc=new RestaurantService(db); var r=await svc.GetBySlugAsync("does-not-exist"); r.Should().BeNull(); }
    [Fact] public async Task Delete_ShouldRemove() { var db=TestDbFactory.CreateInMemory(); var svc=new RestaurantService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id); await svc.DeleteAsync(r.Id); var a=await svc.GetByIdAsync(r.Id); a.Should().BeNull(); }
}

public class CategoryItemToggleTests
{
    [Fact] public async Task ToggleSoldOut_ShouldFlip() { var db=TestDbFactory.CreateInMemory(); var cs=new CategoryService(db); var is2=new MenuItemService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id); var cat=await cs.CreateAsync(new CreateCategoryDto{Name="M",RestaurantId=r.Id}); var item=await is2.CreateAsync(new CreateMenuItemDto{Name="Pizza",Price=100m,CategoryId=cat.Id,IsSoldOut=false}); await is2.ToggleSoldOutAsync(item.Id); var a=await is2.GetByIdAsync(item.Id); a!.IsSoldOut.Should().BeTrue(); }
    [Fact] public async Task ToggleAvailability_ShouldFlip() { var db=TestDbFactory.CreateInMemory(); var cs=new CategoryService(db); var is2=new MenuItemService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id); var cat=await cs.CreateAsync(new CreateCategoryDto{Name="M",RestaurantId=r.Id}); var item=await is2.CreateAsync(new CreateMenuItemDto{Name="Pasta",Price=80m,CategoryId=cat.Id,IsAvailable=true}); await is2.ToggleAvailabilityAsync(item.Id); var a=await is2.GetByIdAsync(item.Id); a!.IsAvailable.Should().BeFalse(); }
    [Fact] public async Task UpdateImage_ShouldSaveUrl() { var db=TestDbFactory.CreateInMemory(); var cs=new CategoryService(db); var is2=new MenuItemService(db); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id); var cat=await cs.CreateAsync(new CreateCategoryDto{Name="M",RestaurantId=r.Id}); var item=await is2.CreateAsync(new CreateMenuItemDto{Name="Burger",Price=120m,CategoryId=cat.Id}); await is2.UpdateImageAsync(item.Id,"/uploads/items/test.jpg"); var a=await is2.GetByIdAsync(item.Id); a!.ImageUrl.Should().Be("/uploads/items/test.jpg"); }
    [Fact] public async Task PublicMenu_UnapprovedNotVisible() { var db=TestDbFactory.CreateInMemory(); var rs=new RestaurantService(db); var cs=new CategoryService(db); var ps=new PublicMenuService(rs,cs); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var r=await TestDbFactory.CreateTestRestaurant(db,owner.Id,false); var m=await ps.GetPublicMenuAsync(r.Slug); m.Should().BeNull(); }
    [Fact] public async Task FullFlow_CreateCategoryAndItems() { var db=TestDbFactory.CreateInMemory(); var rs=new RestaurantService(db); var cs=new CategoryService(db); var is2=new MenuItemService(db); var ps=new PublicMenuService(rs,cs); var um=TestDbFactory.BuildUserManager(db); var owner=await TestDbFactory.CreateTestOwner(um); var rest=await rs.CreateAsync(new CreateRestaurantDto{Name="Test",ThemeColor="#000",CurrencyCode="TRY",CurrencySymbol="₺",SupportedLanguages="tr"},owner.Id); await rs.ApproveAsync(rest.Id); var cat=await cs.CreateAsync(new CreateCategoryDto{Name="Mains",RestaurantId=rest.Id,DisplayOrder=1}); cat.Id.Should().BeGreaterThan(0); await is2.CreateAsync(new CreateMenuItemDto{Name="Steak",Price=200m,CategoryId=cat.Id,IsAvailable=true}); await is2.CreateAsync(new CreateMenuItemDto{Name="Pasta",Price=140m,CategoryId=cat.Id,IsAvailable=true}); var menu=await ps.GetPublicMenuAsync(rest.Slug); menu.Should().NotBeNull(); menu!.Categories.Should().HaveCount(1); menu.Categories[0].Items.Should().HaveCount(2); }
}

public class VerificationTests
{
    [Fact] public async Task Code_ShouldBe6Digits() { var db=TestDbFactory.CreateInMemory(); var svc=new VerificationService(db); var code=await svc.GenerateAndSaveCodeAsync("u1","t@t.com"); code.Should().HaveLength(6).And.MatchRegex("^[0-9]{6}$"); }
    [Fact] public async Task Correct_Code_Verifies() { var db=TestDbFactory.CreateInMemory(); var svc=new VerificationService(db); var code=await svc.GenerateAndSaveCodeAsync("u1","t@t.com"); (await svc.VerifyCodeAsync("u1",code)).Should().BeTrue(); }
    [Fact] public async Task Wrong_Code_Fails() { var db=TestDbFactory.CreateInMemory(); var svc=new VerificationService(db); await svc.GenerateAndSaveCodeAsync("u1","t@t.com"); (await svc.VerifyCodeAsync("u1","000000")).Should().BeFalse(); }
    [Fact] public async Task Used_Code_CannotBeReused() { var db=TestDbFactory.CreateInMemory(); var svc=new VerificationService(db); var code=await svc.GenerateAndSaveCodeAsync("u1","t@t.com"); await svc.VerifyCodeAsync("u1",code); (await svc.VerifyCodeAsync("u1",code)).Should().BeFalse(); }
    [Fact] public async Task Resend_Invalidates_Previous() { var db=TestDbFactory.CreateInMemory(); var svc=new VerificationService(db); var c1=await svc.GenerateAndSaveCodeAsync("u1","t@t.com"); var c2=await svc.GenerateAndSaveCodeAsync("u1","t@t.com"); (await svc.VerifyCodeAsync("u1",c1)).Should().BeFalse(); (await svc.VerifyCodeAsync("u1",c2)).Should().BeTrue(); }
}
